permalink:   /:year/:month/:title.html
timezone:    Europe/Zurich
pygments:    true
markdown:    rdiscount
relative_permalinks: false

categories:
  template: _layouts/archive

archives:
  template: _layouts/archive
