title: Faraway Technologies
description: Faraway Technologies
author: Roman Prokofyev
github: https://github.com/dragoon/dragoon.github.io
about: New-Based Trading at LGT Capital Partners. Tech Advisor at FAIRTIQ.
disqus_shortname: prokofyev
google_analytics: G-V24V0791M4

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "http://twitter.com/rprokofyev"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/rprokofyev"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/dragoon"

share:
  twitter_username: rprokofyev
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://notes.prokofyev.ch"
baseurl: ""
paginate: 20
per_page: 20
relative_permalinks: false
paginate_path: "/blog/page-:num"
permalink:   /:year/:month/:title.html
timezone:    Europe/Zurich
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-archives

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']


category_archive:
  type: jekyll-archives
  path: /category/

jekyll-archives:
  enabled:
    - categories
  layouts:
    category: archive
  permalinks:
    category: '/category/:name.html'


rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants
