permalink:   /:year/:month/:title.html
timezone:    Europe/Zurich
pygments:    true
markdown:    rdiscount
paginate:    20
relative_permalinks: false
paginate_path: /blog/page-:num

categories:
  template: _layouts/archive

archives:
  template: _layouts/archive
