permalink:   /:year/:month/:title.html
timezone:    Europe/Zurich
highlighter: pygments    
paginate:    20
relative_permalinks: false
paginate_path: /blog/page-:num

gems:
  - jekyll-archives

jekyll-archives:
  enabled: 
    - categories
  layout: archive
  permalinks:
    category: '/categories/:name.html'

rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants
