permalink:   /:year/:month/:title.html
timezone:    Europe/Zurich
highlighter: pygments    
markdown:    rdiscount
paginate:    20
relative_permalinks: false
paginate_path: /blog/page-:num

gems:
  - jekyll-archives

jekyll-archives:
  enabled: 
    - categories
  layout: archive
  permalinks:
    category: '/categories/:name.html'
